version: 2
updates:
    - package-ecosystem: "maven"
      directory: "/"
      schedule:
          interval: "daily"
          time: "02:00"
      ignore:
          - dependency-name: "ch.qos.logback:logback-classic"
            update-types: ["major", "minor"]
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
          time: "02:00"
